# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psw', '0002_auto_20160105_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='commands',
            name='wykonana',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='commands',
            name='ip',
            field=models.CharField(max_length=50, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='commands',
            name='quote',
            field=models.IntegerField(verbose_name='Quote'),
        ),
        migrations.AlterField(
            model_name='commands',
            name='ram',
            field=models.IntegerField(verbose_name='Ram'),
        ),
        migrations.AlterField(
            model_name='commands',
            name='system',
            field=models.CharField(max_length=50, verbose_name='System'),
        ),
    ]
