# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psw', '0003_auto_20160106_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('userLogin', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=24)),
            ],
            options={
                'verbose_name': 'Klient',
                'verbose_name_plural': 'Klienci',
            },
        ),
        migrations.RemoveField(
            model_name='commands',
            name='wykonana',
        ),
    ]
